apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbpv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /db
    type: DirectoryOrCreate
