apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbpvc
spec:
  volumeName: dbpv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
