name: Build applications
on: [push]
env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      bot: ${{ steps.filter.outputs.bot }}
      php: ${{ steps.filter.outputs.php }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: dorny/paths-filter@668c092af3649c4b664c54e4b704aa46782f6f7c # v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            bot:
              - 'bot/**'
            PHP:
              - 'PHP/**'
  build:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            path: backend
            image: bklinowski/ctf-backend
            dockerfile: Dockerfiles/backend/Dockerfile
            condition: ${{ needs.changes.outputs.backend == 'true' }}
          - name: bot
            path: bot
            image: bklinowski/ctf-bot
            dockerfile: Dockerfiles/bot/Dockerfile
            condition: ${{ needs.changes.outputs.bot == 'true' }}
          - name: php
            path: php
            image: bklinowski/ctf-php
            dockerfile: Dockerfiles/php/Dockerfile
            condition: ${{ needs.changes.outputs.PHP == 'true' }}
    steps:
      - name: Set up Docker Buildx
        if: ${{ matrix.condition }}
        uses: docker/setup-buildx-action@v3

      - name: Checkout repo
        if: ${{ matrix.condition }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Login to Docker Hub
        if: ${{ matrix.condition }}
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c # v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and push
        if: ${{ matrix.condition }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
