name: Build applications
on: [push]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      bot: ${{ steps.filter.outputs.bot }}
      php: ${{ steps.filter.outputs.php }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: dorny/paths-filter@668c092af3649c4b664c54e4b704aa46782f6f7c # v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            bot:
              - 'bot/**'
            PHP:
              - 'PHP/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: cd backend && docker build -t bklinowski/ctf-backend -f ../Dockerfiles/backend/Dockerfile && docker push bklinowski/ctf-backend

  bot:
    needs: changes
    if: ${{ needs.changes.outputs.bot == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: cd bot && docker build -t bklinowski/ctf-bot -f ../Dockerfiles/bot/Dockerfile && docker push bklinowski/ctf-bot

  PHP:
    needs: changes
    if: ${{ needs.changes.outputs.PHP == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: cd php && docker build -t bklinowski/ctf-php -f ../Dockerfiles/php/Dockerfile && docker push bklinowski/ctf-php
